all:
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  children:
    red_hat_servers:
      hosts:
        server1:
          ansible_host: 54.144.218.66
        server2:
          ansible_host: 54.90.216.247      
      vars:
        ansible_user: ec2-user
