all:
  children:
    amazon:
      hosts:
        test-amazon0:
          ansible_host: 34.201.15.14
        test-amazon1:
          ansible_host: 3.236.191.44
        test-amazon2:
          ansible_host: 100.24.123.205
        test-amazon3:
          ansible_host: 44.214.136.113
        test-amazon4:
          ansible_host: 44.203.63.119
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"